### ISSUE TITLE
Actix.

### ISSUE THREAD

**Issue by uwejan** [mscofield0/vin#6]
Hello there,
I am comming from actix actors background, it is working really good, especially with StreamHandlers, and webscokets, Now the project is growing and needs to put in place some sqlx queries, and that added a ton of issues, as sqlx is async, and self can not move while holding db connection.
I am wondering if this crate would be an easy convert from actix, without lossing much, and gaining async await handle?

Thank you.

**Comment by mscofield0** [comment]
How are you using sqlx exactly? Through a pool or? If you're not using it through a pool, you might find that using it will solve your problem, as queries accepting a pool do not require a `&mut` reference. You would (likely) have the same problems with this crate as you would with Actix since the root cause is most likely a conflict with async and not with the crate itself.

It should be easy converting from Actix to vin, but I do suggest you figure out if you can do something different with your current project.

**Comment by uwejan** [comment]
Hey @mscofield0 Thank you for taking a look into this.
I am using sqlx Pool. you are right the pool can be used as ref, but the problem comes from `async , await`, and the way actix deals with it. Even tried `block_on` it works the cost of blocking the thread which is leading to othre problems with websockets connection being droped as time accures for `PONG`.
I am squeezing my head hoping for a wrok arround, I do realize doing a full conversion to another framework is going to be time intensive. I am still trying to figure it out.

**Comment by mscofield0** [comment]
If you provide a snippet of your code that's relevant, I might have some insight maybe.

**Comment by uwejan** [comment]
Sure, take this db ops handler for example.
```
impl Handler<DbOperations> for McActor {
    type Result = String;
    //type Result = ResponseFuture<String>;
    fn handle(&mut self, msg: DbOperations, ctx: &mut Self::Context) -> Self::Result {
        return match msg {
             DbOperations::Get { key } => {
               block_on(async {
                    sqlx::query_as::<_, DbOperationValues>(msg.select_query)
                        .bind(key)
                        .fetch_one(self.db.as_ref().unwrap())
                        .await
                        .unwrap()
                }).value
                 
            }
            DbOperations::Set { key, value } => {   
                block_on(async {
                    sqlx::query_as::<_, DbOperationValues>(imsg.insert_query)
                        .bind(key)
                        .bind(value)
                        .fetch_one(self.db.as_ref().unwrap())
                        .await
                        .unwrap()
                }).value
            }
        };
    }
}
```

**Comment by uwejan** [comment]
I also tried using `ResponseFuture` but the compiler complains on msg and context must out live static, then i realized it is stated on the docs.

> Intended be used for when the future returned doesn’t need to access Actor’s internal state or context to progress, either because it’s completely agnostic to it, or because the required data has already been moved inside the future and it won’t need Actor state to continue.
https://docs.rs/actix/latest/actix/type.ResponseFuture.html
for Websockets am using `awc` pacakge, which is also on my list to make a convert to tungstien.

**Comment by uwejan** [comment]
I am slo using tauri, that has added a problem a while back where had to run actix a long, whereas had to follow the docs making actix run on tokio, where tauri still did not like so i ended up a calling a new std thread so the actor can run.
TBH, I think there is a place for refinement here and there, but you know that is how it works.

**Comment by mscofield0** [comment]
If you're starting a new tokio task or a new future, you will need to move the context (if it's not `'static`) in order to use it (to satisfy lifetime requirements). The easiest way to do that is to copy-share a `Arc` in all futures.

e.g.
```rust
fn my_actor_handler(&mut self, ctx: &mut Self::Context) {
  let my_data = Arc::clone(&self.data);
  tokio::spawn(async move {
    // my_data.blabla
  });
  // ...
}
```

This means that your data is behind a `&` not a `&mut` though. This is what [this](https://github.com/actix/actix/issues/438) discussion in Actix eventually comes down to.

If you want async/await sugar, then yeah, it might be best to switch to this crate... This crate is being used by me on a complex project and a lot of things that were annoyances before have been fixed, but it's nowhere as battletested as Actix or some other crates are.
